# before_script:
#   - curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
#   - chmod +x /usr/local/bin/docker-compose
#   - ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

build:
  image: docker/compose:latest

  services:
    - docker:dind

  stage: build
  script:
    - docker ps -a
    - pwd
    - ls -la
    - ls -la /etc
    - docker-compose -f docker-compose.test.yml up --build -d

test:
  stage: test
  script:
    - apt-get install python3.9
    - python --version
    - pip install -r ./tests/requirements.txt
    - python ./tests/healthcheck.py
