image: docker/compose:latest

before_script:
  - apk update && apk add openssh

build:
  stage: build
  script:
    - ls -l
    - pwd
    # Ensure that there is no container from previous test runs
    - docker-compose -f docker-compose.test.yml down -v
    - docker build ./tests -t test_service:latest
    - docker-compose -f docker-compose.test.yml up --build --force-recreate -d

test:
  stage: test
  script:
    - docker run --network="testing_network" test_service:latest python healthcheck.py
    - docker run --network="testing_network" test_service:latest python test_apigateway.py
    # Ensure that there is no container from previous test runs
    - docker-compose -f docker-compose.test.yml down -v

deploy:
  stage: deploy
  script:
    - export DEPLOY_ENV=prod
    - sh deploy.sh

