image: docker:latest

services:
  - docker:dind

before_script:
  - docker info

build:
  stage: build
  script:
    - docker ps -a
    - docker-compose up -f /etc/sourcecode/docker-compose.yml --build
