version: "3.8"
services:
  broker_service_test:
    build: ./BrokerService
    hostname: broker_service
    networks:
      testing_network:
        aliases:
          - broker_service

  orig_service_test:
    build: ./OrigService
    hostname: orig_service
    environment:
        - PYTHONUNBUFFERED=1
    networks:
      testing_network:
        aliases:
          - orig_service

  imed_service_test:
    build: ./ImedService
    hostname: imed_service
    networks:
      testing_network:
        aliases:
          - imed_service

  obse_service_test:
    build: ./ObseService
    hostname: obse_service
    volumes:
        - "output_data_test:/output"
    environment:
        - PYTHONUNBUFFERED=1
    networks:
      testing_network:
        aliases:
          - obse_service

  httpserv_service_test:
    build: ./HttpServService
    hostname: httpserv_service
    volumes:
      - "output_data_test:/output"
    networks:
      testing_network:
        aliases:
          - httpserv_service

  apigateway_service_test:
    build: ./APIGatewayService
    hostname: apigateway_service
    networks:
      testing_network:
        aliases:
          - apigateway_service

  state_service_test:
    build: ./StateService
    hostname: state_service
    environment:
    - DOCKER_COMPOSE_FILE=docker-compose.test.yml
    volumes:
      - "output_data_test:/output"
      - "state_data_test:/state"
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/devopsproject:/devopsproject' # ${PROJECT_FILES_PATH}
    networks:
      testing_network:
        aliases:
          - state_service

networks:
  testing_network:
    name: testing_network
volumes:
  output_data_test:
  state_data_test:


