version: "3.8"
services:
  broker_service_test:
    build: ./BrokerService
    hostname: broker_service
    networks:
      testing_network:
        aliases:
          - broker_service

  orig_service_test:
    build: ./OrigService
    hostname: orig_service
    environment:
        - PYTHONUNBUFFERED=1
    networks:
      testing_network:
        aliases:
          - orig_service

  imed_service_test:
    build: ./ImedService
    hostname: imed_service
    networks:
      testing_network:
        aliases:
          - imed_service

  obse_service_test:
    build: ./ObseService
    hostname: obse_service
    volumes:
        - "./output:/output"
    environment:
        - PYTHONUNBUFFERED=1
    networks:
      testing_network:
        aliases:
          - obse_service

  httpserv_service_test:
    build: ./HttpServService
    hostname: httpserv_service
    volumes:
      - "./output:/output"
    networks:
      testing_network:
        aliases:
          - httpserv_service

  test_service:
    build: ./tests
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - testing_network
networks:
  testing_network:
    name: testing_network
