# Used to setup the containers for the test environment.
# Network aliases are used to match the names with the
# production environment.

version: "3.8"
services:
  broker_service_devops_test:
    build: ./BrokerService
    hostname: broker_service
    networks:
      testing_network:
        aliases:
          - broker_service

  orig_service_devops_test:
    build: ./OrigService
    hostname: orig_service
    environment:
        # Enables python to print to console immediately,
        # not after container shutdown
        - PYTHONUNBUFFERED=1
    networks:
      testing_network:
        aliases:
          - orig_service

  imed_service_devops_test:
    build: ./ImedService
    hostname: imed_service
    networks:
      testing_network:
        aliases:
          - imed_service

  obse_service_devops_test:
    build: ./ObseService
    hostname: obse_service
    volumes:
        # Used to share the message log file with other services
        - "output_data_test:/output"
    environment:
        # Enables python to print to console immediately,
        # not after container shutdown
        - PYTHONUNBUFFERED=1
    networks:
      testing_network:
        aliases:
          - obse_service

  httpserv_service_devops_test:
    build: ./HttpServService
    hostname: httpserv_service
    volumes:
      # Used to share the message log file with other services
      - "output_data_test:/output"
    networks:
      testing_network:
        aliases:
          - httpserv_service

  apigateway_service_devops_test:
    build: ./APIGatewayService
    hostname: apigateway_service
    networks:
      testing_network:
        aliases:
          - apigateway_service

  state_service_devops_test:
    build: ./StateService
    hostname: state_service
    environment:
      # The command to shutdown the containers used in this service
      # varies based on this environment variable
    - DEVOPS_PROJECT_ENV=test
    volumes:
      # Used to share the message log file with other services
      - "output_data_test:/output"
      - "state_data_test:/state"
      # Shares the Docker socket of the host machine
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      testing_network:
        aliases:
          - state_service

networks:
  testing_network:
    name: testing_network
volumes:
  output_data_test:
  state_data_test:


