# Used to setup the containers for the production environment.
# Network aliases are used to match the names with the
# test environment.

version: "3.8"
services:
  broker_service_devops_prod:
    build: ./BrokerService
    networks:
      messaging_network:
        aliases:
          - broker_service

  orig_service_devops_prod:
    build: ./OrigService
    environment:
        # Enables python to print to console immediately,
        # not after container shutdown
        - PYTHONUNBUFFERED=1
    networks:
      messaging_network:
        aliases:
          - orig_service

  imed_service_devops_prod:
    build: ./ImedService
    networks:
      messaging_network:
        aliases:
          - imed_service

  obse_service_devops_prod:
    build: ./ObseService
    volumes:
        # Used to share the message log file with other services
        - "output_data:/output"
    environment:
        # Enables python to print to console immediately,
        # not after container shutdown
        - PYTHONUNBUFFERED=1
    networks:
      messaging_network:
        aliases:
          - obse_service

  httpserv_service_devops_prod:
    build: ./HttpServService
    volumes:
      # Used to share the message log file with other services
      - "output_data:/output"
    ports:
      - "8082:8082"
    networks:
      messaging_network:
        aliases:
          - httpserv_service

  apigateway_service_devops_prod:
    build: ./APIGatewayService
    ports:
      - "8081:8081"
    networks:
      messaging_network:
        aliases:
          - apigateway_service

  state_service_devops_prod:
    build: ./StateService
    environment:
      # The command to shutdown the containers used in this service
      # varies based on this environment variable
    - DEVOPS_PROJECT_ENV=prod
    volumes:
      # Used to share the message log file with other services
      - "output_data:/output"
      - "state_data:/state"
      # Shares the Docker socket of the host machine
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      messaging_network:
        aliases:
          - state_service

networks:
  messaging_network:
volumes:
  output_data:
  state_data:
